name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build with Maven
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          BOT_ADMINS: ${{ secrets.BOT_ADMINS }}
          TARGET_CHANNEL: ${{ secrets.TARGET_CHANNEL }}
        run: |
          mvn clean package \
            -DBOT_TOKEN=$BOT_TOKEN \
            -DBOT_USERNAME=$BOT_USERNAME \
            -DBOT_ADMINS=$BOT_ADMINS \
            -DTARGET_CHANNEL=$TARGET_CHANNEL

      - name: Upload to Github Releases (Draft)
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
          tag_name: latest
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}